export const easyWords = [
        'ORANGE', 'PURPLE', 'BANANA', 'GUITAR', 'SUMMER', 'WINTER', 'SPRING', 'AUTUMN', 'FRIEND', 'CANDLE', 'ANIMAL', 'BOTTLE', 'CARROT', 'CIRCLE', 'DESERT', 'FAMILY', 'FLOWER', 'BEAGLE', 'KITTEN', 'LAPTOP', 'LEMON', 'MONKEY', 'OFFICE', 'PEOPLE', 'PICNIC', 'PLEASE', 'PENCIL', 'CAMERA', 'COFFEE', 'PILLOW', 'SOCCER'
];

export const mediumWords = [
    'BREEZY', 'BUNGEE', 'CASTLE', 'DANGER', 'ECLIPSE', 'FABRIC', 'GARDEN', 'HELIUM', 'INSECT', 'JIGSAW', 'KNIGHT', 'LIZARD', 'MAKEUP', 'NEEDLE', 'OXYGEN', 'PALACE', 'ROCKET', 'SAFARI', 'KEYPAD', 'TUNNEL', 'ABSURD', 'BISHOP', 'CRUSTY', 'DECADE', 'ENIGMA', 'FELINE', 'GALAXY', 'HAZARD', 'IGNITE', 'JUMBLE', 'KERNEL', 'MAMMAL', 'ORACLE', 'PLASMA', 'QUIVER', 'REMOTE', 'TRAGIC'
];

export const hardWords = [
    'ABACUS', 'EMBODY', 'FIASCO', 'GNARLE', 'JARGON', 'LACTOSE', 'MUFFLE', 'PUNDIT', 'RANCOR', 'SIEGE', 'TUNDRA', 'ALIGHT', 'BAFFLE', 'CANOPY', 'DEARTH', 'ELAPSE', 'FATHOM', 'GLISTEN', 'HURDLE', 'JUGGLE', 'KUDOS', 'LAVISH', 'NURTURE', 'ORDEAL', 'QUENCH', 'ROBUST', 'SORDID', 'TURBUL', 'QUOKKA', 'LICHEN', 'SCHEMA', 'NUANCE'
];
